name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: bash build.sh
      - name: Archive bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: tmp/dist/file-backup-0.1.0-SNAPSHOT.zip
